# Generated by Django 5.1.15 on 2026-08-07 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(choices=[('choice', 'Múltiple opción'), ('oral', 'Oral')], default='choice', max_length=10, verbose_name='Tipo')),
                ('difficulty', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Media'), ('hard', 'Difícil')], default='medium', max_length=10, verbose_name='Dificultad')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año cursada')),
                ('statement', models.TextField(verbose_name='Enunciado')),
                ('explanation', models.TextField(blank=True, verbose_name='Explicación / Resolución')),
                ('image', models.ImageField(blank=True, null=True, upload_to='simulator/questions/', verbose_name='Imagen')),
                ('tags', models.CharField(blank=True, help_text='Separar con comas', max_length=300)),
                ('source', models.CharField(choices=[('unlp', 'UNLP Oficial'), ('alumed', 'ALUMED'), ('profe', 'Profe Joy'), ('other', 'Otro')], default='alumed', max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['subject', 'difficulty', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Materia')),
                ('emoji', models.CharField(default='📚', max_length=8)),
                ('year', models.PositiveSmallIntegerField(choices=[(1, '1° Año'), (2, '2° Año'), (3, '3° Año'), (4, '4° Año'), (5, '5° Año'), (6, '6° Año')], default=1, verbose_name='Año')),
                ('color', models.CharField(default='#8b5cf6', help_text='Color hex para UI', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'ordering': ['year', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Alternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto de la opción')),
                ('is_correct', models.BooleanField(default=False, verbose_name='¿Es correcta?')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='simulator.question')),
            ],
            options={
                'verbose_name': 'Alternativa',
                'verbose_name_plural': 'Alternativas',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='simulator.subject'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tema')),
                ('active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='simulator.subject')),
            ],
            options={
                'verbose_name': 'Tema',
                'verbose_name_plural': 'Temas',
                'ordering': ['order', 'name'],
                'unique_together': {('subject', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SimSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('choice', 'Múltiple opción'), ('oral', 'Oral'), ('unlp', 'Modo UNLP')], default='choice', max_length=10)),
                ('difficulty', models.CharField(blank=True, max_length=10)),
                ('preset', models.CharField(blank=True, help_text='Nombre del preset UNLP', max_length=60)),
                ('total_q', models.PositiveSmallIntegerField(default=0, verbose_name='Total preguntas')),
                ('correct', models.PositiveSmallIntegerField(default=0, verbose_name='Correctas')),
                ('score', models.FloatField(default=0.0, verbose_name='% acierto')),
                ('duration_s', models.PositiveIntegerField(default=0, verbose_name='Duración (segundos)')),
                ('status', models.CharField(choices=[('active', 'En curso'), ('finished', 'Finalizado')], default='active', max_length=10)),
                ('question_order', models.JSONField(blank=True, default=list)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('time_limit_s', models.PositiveIntegerField(default=0, help_text='0 = sin límite')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_sessions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.subject')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simulator.topic')),
            ],
            options={
                'verbose_name': 'Sesión de Simulado',
                'verbose_name_plural': 'Sesiones de Simulado',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='simulator.topic'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_s', models.PositiveSmallIntegerField(default=0, verbose_name='Tiempo (s)')),
                ('oral_text', models.TextField(blank=True, verbose_name='Respuesta oral escrita')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='Feedback IA')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('chosen_alts', models.ManyToManyField(blank=True, to='simulator.alternative', verbose_name='Opciones elegidas')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='simulator.simsession')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['subject', 'q_type', 'active'], name='simulator_q_subject_fcc864_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='simulator_q_topic_i_ba863d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'question')},
        ),
    ]
