# Generated by Django 5.2.9 on 2025-12-31 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(help_text='Si el evento dura solo un día, esta fecha debe ser igual a la de inicio.', verbose_name='Fecha de Fin')),
                ('event_type', models.CharField(choices=[('exam', 'Examen'), ('notice', 'Aviso')], max_length=10, verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento del Calendario',
                'verbose_name_plural': 'Eventos del Calendario',
                'ordering': ['start_date'],
            },
        ),
    ]
