# Generated by Django 5.2.9 on 2026-01-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('file', models.FileField(upload_to='library/', verbose_name='Archivo')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/covers/', verbose_name='Imagen de Portada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Recurso de Biblioteca',
                'verbose_name_plural': 'Biblioteca Virtual',
                'ordering': ['-created_at'],
            },
        ),
    ]
