# Generated by Django 5.2.9 on 2026-01-02 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_libraryresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryresource',
            name='file',
        ),
        migrations.AddField(
            model_name='libraryresource',
            name='download_url',
            field=models.URLField(default='', help_text='Pegue aquí el enlace del archivo', verbose_name='Link de Descarga (Google Cloud)'),
        ),
    ]
