# Generated by Django 5.2.9 on 2026-01-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_libraryresource_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('image', models.ImageField(upload_to='store/products/', verbose_name='Imagen del Producto')),
                ('whatsapp_link', models.URLField(blank=True, help_text='Deje en blanco para generar automáticamente.', null=True, verbose_name='Enlace de WhatsApp')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Tienda Alumed',
                'ordering': ['-created_at'],
            },
        ),
    ]
