# Generated by Django 5.2.9 on 2026-01-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
