# Generated by Django 5.1.4 on 2026-02-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título (Opcional)')),
                ('message', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('link_text', models.CharField(default='Ver más', max_length=50, verbose_name='Texto del Botón')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='URL del Botón')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Popup Promocional',
                'verbose_name_plural': 'Popups Promocionales',
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/', verbose_name='Imagen'),
        ),
    ]
