# Generated by Django 5.1.4 on 2026-02-07 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_popup_announcement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='popups/', verbose_name='Imagen (Opcional)'),
        ),
    ]
