# Generated by Django 5.1.4 on 2026-02-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_popup_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Estudiante')),
                ('role', models.CharField(default='Estudiante', max_length=100, verbose_name='Rol/Curso')),
                ('text', models.TextField(verbose_name='Testimonio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/', verbose_name='Foto de Perfil')),
                ('initial', models.CharField(blank=True, max_length=2, verbose_name='Inicial (si no hay foto)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Testimonio',
                'verbose_name_plural': 'Testimonios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Video')),
                ('video_url', models.URLField(help_text='Link directo al video.', verbose_name='URL del Video (Cloud/YouTube)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='testimonials/thumbnails/', verbose_name='Miniatura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Video Testimonio',
                'verbose_name_plural': 'Videos Testimonios',
                'ordering': ['-created_at'],
            },
        ),
    ]
