# Generated by Django 5.1.15 on 2026-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_testimonial_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('subject', models.CharField(choices=[('histo', 'Histología'), ('embrio', 'Embriología'), ('bio', 'Biología'), ('anato', 'Anatomía'), ('transcripcion', 'Factores de Transcripción'), ('simulacros', 'Simulacros y Exámenes')], max_length=20, verbose_name='Materia/Categoría')),
                ('category', models.CharField(default='Apunte Completo', max_length=50, verbose_name='Tema/Subcategoría')),
                ('year', models.CharField(default='1º Año', max_length=20, verbose_name='Año')),
                ('platform', models.CharField(default='Studocu', max_length=50, verbose_name='Plataforma')),
                ('pdf_url', models.URLField(blank=True, verbose_name='Enlace de la Fuente Original')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='Autor')),
                ('page_count', models.IntegerField(default=1, verbose_name='Cantidad de Páginas')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('posible', 'Posible'), ('duplicado', 'Duplicado'), ('revisar', 'Revisar')], default='confirmado', max_length=20, verbose_name='Estado')),
                ('tags', models.CharField(blank=True, help_text='Separadas por coma', max_length=255, verbose_name='Etiquetas')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='library/covers/', verbose_name='Imagen de Portada')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='library/pdfs/', verbose_name='Archivo PDF Local')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto Extraído')),
                ('ai_summary', models.TextField(blank=True, verbose_name='Resumen de IA')),
                ('ai_flashcards', models.JSONField(blank=True, null=True, verbose_name='Flashcards de IA')),
                ('ai_quiz', models.JSONField(blank=True, null=True, verbose_name='Quiz de IA')),
                ('joy_method', models.JSONField(blank=True, null=True, verbose_name='Método Joy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Libro Digital',
                'verbose_name_plural': 'Libros Digitales',
                'ordering': ['subject', '-created_at'],
            },
        ),
    ]
