# Generated by Django 5.1.15 on 2026-07-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_digitalbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteleraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, help_text='Extraído do path /noticia/<id>', max_length=100, unique=True, verbose_name='ID externo')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 de título+data+emissor — detecta mudanças', max_length=64, verbose_name='Hash do conteúdo')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtítulo')),
                ('issuer', models.CharField(blank=True, max_length=300, verbose_name='Organismo emissor')),
                ('date_str', models.CharField(blank=True, max_length=30, verbose_name='Data (texto original)')),
                ('date_parsed', models.DateField(blank=True, null=True, verbose_name='Data (parseada)')),
                ('url', models.URLField(max_length=500, verbose_name='URL original')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='Categoria/Matéria')),
                ('first_seen_at', models.DateTimeField(auto_now_add=True, verbose_name='Primeira vez visto')),
                ('last_seen_at', models.DateTimeField(auto_now=True, verbose_name='Última vez visto')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Notificado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ainda ativo na cartelera')),
            ],
            options={
                'verbose_name': 'Aviso da Cartelera',
                'verbose_name_plural': 'Avisos da Cartelera',
                'ordering': ['-date_parsed', '-first_seen_at'],
                'indexes': [models.Index(fields=['date_parsed', 'is_active'], name='core_cartel_date_pa_dcf7ec_idx'), models.Index(fields=['notified_at'], name='core_cartel_notifie_17656b_idx')],
            },
        ),
    ]
