# Generated by Django 5.1.15 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cartelera_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteleraitem',
            name='target_years',
            field=models.CharField(blank=True, default='', help_text='Vazio = todos os alunos. Ex: "ingreso,1,2" = só esses anos.', max_length=100, verbose_name='Anos alvo'),
        ),
    ]
