# Generated by Django 5.1.15 on 2026-07-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_cartelera_target_years'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteleraitem',
            name='attachment_urls',
            field=models.JSONField(default=list, verbose_name='Links e PDFs anexados'),
        ),
        migrations.AddField(
            model_name='carteleraitem',
            name='body_text',
            field=models.TextField(blank=True, verbose_name='Conteúdo completo do aviso'),
        ),
        migrations.AddField(
            model_name='carteleraitem',
            name='is_deep_scraped',
            field=models.BooleanField(default=False, verbose_name='Raspagem profunda concluída'),
        ),
    ]
