# Generated by Django 5.1.15 on 2026-07-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cartelera_deep_scraping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalbook',
            name='subject',
            field=models.CharField(choices=[('histo', 'Histología'), ('embrio', 'Embriología'), ('bio', 'Biología'), ('anato', 'Anatomía'), ('transcripcion', 'Factores de Transcripción'), ('simulacros', 'Simulacros y Exámenes'), ('quimica', 'Química Biológica / Bioquímica'), ('fisio', 'Fisiología y Biofísica'), ('micro', 'Microbiología y Parasitología'), ('pato', 'Patología'), ('farma', 'Farmacología'), ('semiologia', 'Semiología y Medicina Interna'), ('pediatria', 'Pediatría'), ('ginecologia', 'Ginecología y Obstetricia'), ('cirugia', 'Cirugía'), ('clinica', 'Clínica Médica'), ('otras', 'Otras Asignaturas')], max_length=20, verbose_name='Materia/Categoría'),
        ),
    ]
