# Generated by Django 5.1.15 on 2026-07-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_digitalbook_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalbook',
            name='pdf_url',
            field=models.URLField(blank=True, max_length=1500, verbose_name='Enlace de la Fuente Original'),
        ),
    ]
