# Generated by Django 5.1.15 on 2026-08-07 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_digitalbook_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAluMedAdept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254, unique=True)),
                ('wix_subscription_id', models.CharField(blank=True, max_length=100)),
                ('has_atlas_access', models.BooleanField(default=False)),
                ('has_microscope_access', models.BooleanField(default=False)),
                ('has_profe_joy_premium', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '💎 Adepto del Club (Acceso)',
                'verbose_name_plural': '💎 Adeptos del Club',
            },
        ),
        migrations.CreateModel(
            name='ConectaRadarSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
                ('auth_cookies', models.JSONField(help_text='Cookies serializadas de la sesión')),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '📡 Sesión Radar (Nodo Activo)',
                'verbose_name_plural': '📡 Sesiones Radar',
            },
        ),
        migrations.CreateModel(
            name='EstatutoCodex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('legal_text', models.TextField()),
                ('keywords', models.CharField(help_text='Ej: recursante, extranjero, correlatividad', max_length=255)),
            ],
            options={
                'verbose_name': '⚖️ Códice del Estatuto (Regla)',
                'verbose_name_plural': '⚖️ Códices del Estatuto',
            },
        ),
        migrations.CreateModel(
            name='FirewallSigil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=100)),
                ('token_hash', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('rate_limit_requests', models.IntegerField(default=100, help_text='Reqs por minuto')),
                ('rotated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '🔥 Sello de Fuego (API Key)',
                'verbose_name_plural': '🔥 Sellos de Fuego',
            },
        ),
        migrations.CreateModel(
            name='PrimeiroBiblioTome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='biblioteca_raw/')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(help_text='Ej: Anatomía, Histología', max_length=100)),
                ('vectorization_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado')], default='PENDING', max_length=20)),
                ('total_chunks', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '📚 Tomo de Biblioteca (RAG)',
                'verbose_name_plural': '📚 Tomos de Biblioteca',
            },
        ),
        migrations.CreateModel(
            name='RadarSweepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_year', models.IntegerField(choices=[(0, 'Ingreso'), (1, '1º Año'), (2, '2º Año'), (3, '3º Año')])),
                ('endpoint_scraped', models.URLField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Éxito'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error')], max_length=50)),
                ('items_found', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🧿 Log de Varredura (Sweep)',
                'verbose_name_plural': '🧿 Logs de Varredura',
            },
        ),
        migrations.CreateModel(
            name='AegisDefenseDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_identifier', models.CharField(max_length=100)),
                ('generated_document', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estatutocodex')),
            ],
            options={
                'verbose_name': '🛡️ Escudo Legal (Borrador)',
                'verbose_name_plural': '🛡️ Escudos Legales',
            },
        ),
    ]
