# Generated by Django 5.1.15 on 2026-08-07 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_clubalumedadept_conectaradarsession_estatutocodex_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_event_id', models.CharField(max_length=255)),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('cartelera_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_syncs', to='core.carteleraitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synced_calendar_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cartelera_event')},
            },
        ),
    ]
