# Generated by Django 5.1.15 on 2026-08-07 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_usercalendarevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Materia')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Interno')),
                ('ano_cursada', models.IntegerField(help_text='1, 2, 3...', verbose_name='Año de Cursada')),
            ],
        ),
        migrations.CreateModel(
            name='CursoWix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título del Curso')),
                ('wix_course_url', models.URLField(max_length=500, verbose_name='URL del Curso en Wix')),
                ('imagen_portada', models.URLField(blank=True, max_length=500, verbose_name='URL de la Imagen')),
                ('descripcion_corta', models.CharField(blank=True, max_length=300, verbose_name='Descripción corta')),
                ('activo', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cursos_wix', to='core.materia')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_url', models.URLField(blank=True, max_length=500)),
                ('bio', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('wix_member_id', models.CharField(blank=True, max_length=255, null=True)),
                ('materias', models.ManyToManyField(blank=True, related_name='estudiantes', to='core.materia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='core_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
