# Generated by Django 5.1.15 on 2026-08-07 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_materia_cursowix_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de WhatsApp en formato E.164, ej: +5492211234567', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='WhatsAppMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('message_type', models.CharField(choices=[('welcome', 'Bienvenida'), ('event_alert', 'Alerta de Evento/Examen'), ('exam_reminder', 'Recordatorio'), ('support', 'Soporte')], max_length=50)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('sent', 'Enviado'), ('failed', 'Fallido')], default='queued', max_length=20)),
                ('api_response_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
