# Generated by Django 5.1.15 on 2026-08-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_librarydownloadlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='carteleraitem',
            name='target_year',
            field=models.CharField(blank=True, help_text='Ej: Primer Año, Segundo Año, Medicina 2026', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_year',
            field=models.CharField(blank=True, help_text='Año académico del alumno', max_length=50, null=True),
        ),
    ]
