# Generated by Django 5.1.15 on 2026-08-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_carteleraitem_target_year_userprofile_current_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título de la Clase')),
                ('stream_url', models.URLField(max_length=500, verbose_name='URL del Streaming (Embed)')),
                ('target_year', models.CharField(blank=True, help_text='Ej: Ingreso, Primer Año, Segundo Año', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='En Vivo Ahora')),
                ('scheduled_time', models.DateTimeField(verbose_name='Fecha y Hora Programada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '🔴 Clase en Vivo',
                'verbose_name_plural': '🔴 Clases en Vivo',
                'ordering': ['-scheduled_time'],
            },
        ),
    ]
