# Generated by Django 5.1.15 on 2026-07-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_topic_options_topic_file_alter_topic_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.CharField(choices=[('anatomia', 'Anatomía'), ('biologia', 'Biología'), ('histologia', 'Histología y Embriología'), ('sociales', 'Ciencias Sociales y Medicina'), ('fisiologia', 'Fisiología y Física Biológica'), ('bioquimica', 'Bioquímica y Biología Molecular'), ('psicologia', 'Psicología Médica'), ('farmacologia', 'Farmacología Básica'), ('microbiologia', 'Microbiología y Parasitología'), ('patologia', 'Patología'), ('semiologia', 'Semiología')], default='histologia', max_length=50, verbose_name='Materia'),
        ),
    ]
