# Generated by Django 5.2.9 on 2026-01-06 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_announcement_view_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
