# Generated by Django 5.1.15 on 2026-07-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_last_announcement_view_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wix_member_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
