# Generated by Django 5.1.15 on 2026-07-16 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_wix_member_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('CONECTA_FCM', 'Conecta FCM'), ('ALUMED_CAMPUS', 'ALUMED Campus (Premium)'), ('CLUB_ALUMED', 'Club ALUMED')], max_length=50, unique=True, verbose_name='Identificador do Produto')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descricao')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto de Acesso',
                'verbose_name_plural': 'Produtos de Acesso',
            },
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Concedido em')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Deixar em branco = sem expiracao', null=True, verbose_name='Expira em')),
                ('source', models.CharField(choices=[('wix', 'Wix Webhook'), ('manual', 'Manual Staff'), ('transferencia', 'Transferencia Bancaria'), ('cortesia', 'Cortesia')], default='manual', max_length=20, verbose_name='Origem')),
                ('notes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='accounts.accessproduct', verbose_name='Produto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acesso de Usuario',
                'verbose_name_plural': 'Acessos de Usuarios',
                'ordering': ['-granted_at'],
                'unique_together': {('user', 'product')},
            },
        ),
    ]
