# Generated by Django 5.1.15 on 2026-07-16 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_accessproduct_useraccess'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConectaConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('granted', 'Concedido'), ('revoked', 'Revocado')], max_length=10, verbose_name='Acción')),
                ('version', models.CharField(max_length=10, verbose_name='Versión del consentimiento')),
                ('channels', models.CharField(blank=True, max_length=100, verbose_name='Canales autorizados')),
                ('whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp registrado')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email registrado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/hora')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Evento de Consentimiento',
                'verbose_name_plural': 'Eventos de Consentimiento',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConectaPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Normalizado a E.164: +5492211234567', max_length=20, verbose_name='WhatsApp del alumno')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='Email del alumno')),
                ('whatsapp_active', models.BooleanField(default=False, verbose_name='Alertas WhatsApp activas')),
                ('email_active', models.BooleanField(default=False, verbose_name='Alertas Email activas')),
                ('calendar_active', models.BooleanField(default=False, verbose_name='Sincronización Google Calendar')),
                ('consent_granted', models.BooleanField(default=False, verbose_name='Consentimiento otorgado')),
                ('consent_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha del último consentimiento')),
                ('consent_version', models.CharField(default='v1', max_length=10, verbose_name='Versión del consentimiento')),
                ('consent_channels', models.CharField(blank=True, help_text='whatsapp,email,calendar', max_length=100, verbose_name='Canales autorizados')),
                ('is_active', models.BooleanField(default=True, verbose_name='Cuenta activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conecta_preference', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia Conecta FCM',
                'verbose_name_plural': 'Preferencias Conecta FCM',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConectaSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('institutional', 'Información Institucional'), ('subject', 'Materia de Medicina')], max_length=15, verbose_name='Tipo')),
                ('key', models.CharField(max_length=120, verbose_name='Slug canónico')),
                ('enabled', models.BooleanField(default=True, verbose_name='Activa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conecta_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Suscripción Conecta FCM',
                'verbose_name_plural': 'Suscripciones Conecta FCM',
                'indexes': [models.Index(fields=['user', 'type', 'enabled'], name='idx_conecta_sub_user_type_en')],
                'constraints': [models.UniqueConstraint(fields=('user', 'type', 'key'), name='unique_conecta_subscription')],
            },
        ),
    ]
