# Generated by Django 5.1.15 on 2026-07-16 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_conecta_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='Materia')),
                ('event_type', models.CharField(choices=[('final', 'Final'), ('parcial', 'Parcial'), ('tp', 'TP'), ('inscripcion', 'Inscripción'), ('clase', 'Clase especial'), ('simulacro', 'Simulacro'), ('meta', 'Meta personal'), ('otro', 'Otro')], max_length=15, verbose_name='Tipo')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y hora')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lugar/Aula')),
                ('notes', models.TextField(blank=True, verbose_name='Observaciones')),
                ('registration_open_at', models.DateTimeField(blank=True, null=True, verbose_name='Apertura de inscripción')),
                ('registration_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Cierre de inscripción')),
                ('registration_confirmed', models.BooleanField(default=False, verbose_name='Inscripción confirmada')),
                ('inscription_alert_dismissed', models.BooleanField(default=False, verbose_name='Alerta descartada')),
                ('google_event_id', models.CharField(blank=True, max_length=300, verbose_name='ID Google Calendar')),
                ('google_calendar_id', models.CharField(blank=True, max_length=300, verbose_name='Calendar ID')),
                ('google_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='Último sync Google')),
                ('status', models.CharField(choices=[('pending', 'Inscripción pendiente'), ('open', 'Inscripción abierta'), ('upcoming', 'Próximo'), ('done', 'Realizado')], default='upcoming', max_length=15, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Académico',
                'verbose_name_plural': 'Eventos Académicos',
                'ordering': ['start_datetime'],
                'indexes': [models.Index(fields=['user', 'start_datetime'], name='idx_academic_event_user_dt')],
            },
        ),
    ]
