# Generated by Django 5.1.15 on 2026-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_avatar_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(blank=True, choices=[('', 'Não informado'), ('ingreso', 'Ingreso'), ('1', '1° Año'), ('2', '2° Año'), ('3', '3° Año'), ('4', '4° Año'), ('5', '5° Año'), ('6', '6° Año'), ('internado', 'Internado')], default='', help_text='Informe em qual ano da FCM-UNLP voce esta.', max_length=10, verbose_name='Ano na carreira'),
        ),
    ]
