# Generated by Django 5.1.15 on 2026-07-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID Telegram')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='@usuario')),
                ('year', models.CharField(choices=[('ingreso', 'Ingreso'), ('1', '1° Año'), ('2', '2° Año'), ('3', '3° Año'), ('4', '4° Año'), ('5', '5° Año'), ('6', '6° Año'), ('internado', 'Internado'), ('todos', 'Todos los años')], default='todos', max_length=10, verbose_name='Año académico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Suscriptor Telegram',
                'verbose_name_plural': 'Suscriptores Telegram',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
