# Generated by Django 5.1.15 on 2026-07-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_telegram_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfeJoyChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Título do material')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL da fonte')),
                ('content', models.TextField(verbose_name='Conteúdo do chunk')),
                ('embedding', models.JSONField(default=list, verbose_name='Vetor de embedding')),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('url', 'Página Web'), ('text', 'Texto Manual')], default='pdf', max_length=10)),
                ('chunk_index', models.PositiveIntegerField(default=0, verbose_name='Índice do chunk')),
                ('year', models.CharField(blank=True, help_text='1,2,3... ou vazio para geral', max_length=20, verbose_name='Ano letivo alvo')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Matéria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profe Joy — Chunk',
                'verbose_name_plural': 'Profe Joy — Chunks',
                'ordering': ['title', 'chunk_index'],
                'indexes': [models.Index(fields=['title'], name='idx_profejoy_title'), models.Index(fields=['year'], name='idx_profejoy_year')],
            },
        ),
    ]
