# Generated by Django 5.1.15 on 2026-07-20 21:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('subject', models.CharField(db_index=True, max_length=120)),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=2)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('accuracy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='medlatin.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlatin_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RootEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(max_length=120)),
                ('normalized_form', models.CharField(db_index=True, max_length=120)),
                ('root_type', models.CharField(choices=[('prefix', 'Prefix'), ('root', 'Root'), ('suffix', 'Suffix'), ('preposition', 'Preposition'), ('combining_form', 'Combining form')], db_index=True, max_length=20)),
                ('origin_language', models.CharField(db_index=True, max_length=120)),
                ('original_script', models.CharField(blank=True, max_length=120)),
                ('core_meaning', models.CharField(max_length=255)),
                ('explanation', models.TextField(blank=True)),
                ('mnemonic', models.TextField(blank=True)),
                ('variants', models.CharField(blank=True, max_length=255)),
                ('common_combinations', models.TextField(blank=True)),
                ('subjects', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['form'],
                'constraints': [models.UniqueConstraint(fields=('normalized_form', 'root_type'), name='unique_root_form_type')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('latin_name', models.CharField(db_index=True, max_length=180)),
                ('standard_term', models.CharField(blank=True, max_length=180)),
                ('pronunciation', models.CharField(blank=True, max_length=180)),
                ('audio_url', models.URLField(blank=True)),
                ('grammatical_class', models.CharField(blank=True, db_index=True, max_length=80)),
                ('gender', models.CharField(blank=True, db_index=True, max_length=40)),
                ('declension', models.CharField(blank=True, db_index=True, max_length=60)),
                ('literal_translation', models.TextField()),
                ('medical_definition', models.TextField()),
                ('etymology', models.TextField()),
                ('naming_logic', models.TextField()),
                ('naming_category', models.CharField(blank=True, db_index=True, max_length=100)),
                ('mnemonic', models.TextField(blank=True)),
                ('mnemonic_spanish', models.TextField(blank=True)),
                ('mnemonic_portuguese', models.TextField(blank=True)),
                ('exam_trap', models.TextField(blank=True)),
                ('rapid_review', models.TextField(blank=True)),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=120)),
                ('subject', models.CharField(blank=True, db_index=True, max_length=120)),
                ('anatomical_system', models.CharField(blank=True, db_index=True, max_length=120)),
                ('anatomical_region', models.CharField(blank=True, max_length=120)),
                ('difficulty', models.PositiveSmallIntegerField(db_index=True, default=2)),
                ('origin_language', models.CharField(db_index=True, max_length=160)),
                ('term_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('validation_status', models.CharField(choices=[('draft', 'Draft'), ('ai_draft', 'AI-assisted draft'), ('reviewed', 'Reviewed'), ('validated', 'Medically validated')], db_index=True, default='ai_draft', max_length=24)),
                ('source_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['latin_name'],
                'indexes': [models.Index(fields=['latin_name', 'origin_language'], name='medlatin_te_latin_n_3d4600_idx'), models.Index(fields=['subject', 'anatomical_system'], name='medlatin_te_subject_9e56ce_idx'), models.Index(fields=['validation_status', 'difficulty'], name='medlatin_te_validat_162f6b_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('matching', 'Matching'), ('fill_blank', 'Fill in the blank'), ('decomposition', 'Word decomposition'), ('true_false', 'True or false'), ('incorrect_etymology', 'Incorrect etymology'), ('naming_logic', 'Naming logic'), ('exam_trap', 'Exam trap')], max_length=32)),
                ('prompt', models.TextField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('explanation', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='medlatin.quiz')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_questions', to='medlatin.term')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MedicalExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(db_index=True, max_length=120)),
                ('title', models.CharField(max_length=180)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('pt-BR', 'Portuguese'), ('en', 'English')], max_length=10)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='medlatin.term')),
            ],
            options={
                'ordering': ['context', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(db_index=True, max_length=60)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='medlatin.term')),
            ],
            options={
                'ordering': ['term__latin_name', 'card_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FlashcardReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('again', 'Again'), ('hard', 'Hard'), ('good', 'Good'), ('easy', 'Easy')], default='good', max_length=12)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('next_review', models.DateTimeField(blank=True, null=True)),
                ('interval', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.DecimalField(decimal_places=2, default=2.5, max_digits=4)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('mistake_count', models.PositiveIntegerField(default=0)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='medlatin.flashcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlatin_flashcard_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review', 'id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'flashcard'), name='unique_medlatin_flashcard_review')],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('synonym', 'Synonym'), ('antonym', 'Antonym'), ('derived_term', 'Derived term'), ('same_root', 'Same root'), ('parent_concept', 'Parent concept'), ('child_concept', 'Child concept'), ('neighboring_structure', 'Neighboring structure'), ('frequently_confused', 'Frequently confused')], db_index=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('source_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='medlatin.term')),
                ('target_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='medlatin.term')),
            ],
            options={
                'ordering': ['relationship_type', 'target_term__latin_name'],
                'constraints': [models.UniqueConstraint(fields=('source_term', 'target_term', 'relationship_type'), name='unique_medlatin_relationship')],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlatin_favorites', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='medlatin.term')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'term'), name='unique_medlatin_favorite')],
            },
        ),
        migrations.CreateModel(
            name='TermRootLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_links', to='medlatin.rootentry')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_links', to='medlatin.term')),
            ],
            options={
                'ordering': ['display_order', 'root__form'],
                'constraints': [models.UniqueConstraint(fields=('term', 'root'), name='unique_term_root_link')],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('es', 'Spanish'), ('pt-BR', 'Portuguese'), ('en', 'English')], db_index=True, max_length=10)),
                ('text', models.CharField(db_index=True, max_length=220)),
                ('translation_type', models.CharField(default='preferred', max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='medlatin.term')),
            ],
            options={
                'ordering': ['language', 'text'],
                'constraints': [models.UniqueConstraint(fields=('term', 'language', 'translation_type'), name='unique_term_translation_type')],
            },
        ),
        migrations.CreateModel(
            name='UserTermProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('learning', 'Learning'), ('mastered', 'Mastered')], default='learning', max_length=20)),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('mastery_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('private_notes', models.TextField(blank=True)),
                ('study_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='medlatin.term')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medlatin_term_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'term'), name='unique_medlatin_term_progress')],
            },
        ),
        migrations.CreateModel(
            name='WordPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(choices=[('prefix', 'Prefix'), ('root', 'Root'), ('combining_vowel', 'Combining vowel'), ('suffix', 'Suffix'), ('compound_element', 'Compound element'), ('whole_lexical_unit', 'Whole lexical unit')], db_index=True, max_length=24)),
                ('form', models.CharField(max_length=120)),
                ('normalized_form', models.CharField(db_index=True, max_length=120)),
                ('meaning', models.CharField(max_length=255)),
                ('origin_language', models.CharField(max_length=120)),
                ('grammatical_function', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('confidence', models.DecimalField(decimal_places=2, default=1, max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_parts', to='medlatin.term')),
            ],
            options={
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['normalized_form', 'part_type'], name='medlatin_wo_normali_28a23e_idx')],
            },
        ),
    ]
