# Generated by Django 5.1.4 on 2026-01-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição da aula (pode conter links e texto).', null=True),
        ),
    ]
