# Generated by Django 5.0.2 on 2026-01-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_create_podcastepisode_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='html_url',
            field=models.URLField(blank=True, help_text='URL do arquivo HTML hospedado (ex: Google Cloud). Se preenchido, o conteúdo HTML será carregado via iframe.', null=True),
        ),
    ]
