# Generated by Django 5.1.4 on 2026-01-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_html_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='simulacro_url',
            field=models.URLField(blank=True, help_text='URL do Simulacro (HTML externo ou arquivo hospedado). Será exibido em iframe.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('html', 'HTML'), ('podcast', 'Podcast'), ('simulacro', 'Simulacro')], default='video', max_length=10),
        ),
    ]
