# Generated by Django 5.1.4 on 2026-01-16 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_simulacro_url_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_id',
            field=models.CharField(blank=True, help_text='ID do pagamento no Mercado Pago', max_length=100, null=True, unique=True),
        ),
    ]
