# Generated by Django 5.1.4 on 2026-01-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_deck_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='category',
            field=models.CharField(choices=[('anatomia', 'Anatomía'), ('fisiologia', 'Fisiología'), ('farmacologia', 'Farmacología'), ('patologia', 'Patología'), ('histologia', 'Histología'), ('bioquimica', 'Bioquímica'), ('microbiologia', 'Microbiología'), ('otros', 'Otros')], default='otros', max_length=50, verbose_name='Categoría'),
        ),
    ]
