# Generated by Django 5.1.4 on 2026-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_deck_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='category',
            field=models.CharField(default='General', max_length=100, verbose_name='Categoría'),
        ),
    ]
