# Generated by Django 5.1.4 on 2026-01-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_deck_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('html', 'HTML'), ('podcast', 'Podcast'), ('simulacro', 'Simulacro'), ('special_html', 'Contenido Especial HTML')], default='video', max_length=20),
        ),
    ]
