# Generated by Django 5.1.4 on 2026-01-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='special_content_url',
            field=models.URLField(blank=True, help_text='URL para redirecionamento (Conteúdo Especial).', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('html', 'HTML'), ('podcast', 'Podcast'), ('simulacro', 'Simulacro'), ('special_content', 'Conteúdo Especial')], default='video', max_length=15),
        ),
    ]
