# Generated by Django 5.1.4 on 2026-02-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_lesson_special_content_url_alter_lesson_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Curso Gratuito'),
        ),
    ]
