# Generated by Django 5.1.15 on 2026-04-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_provider',
            field=models.CharField(choices=[('auto', 'Detectar automaticamente'), ('google_cloud', 'Google Cloud Storage'), ('youtube', 'YouTube'), ('google_drive', 'Google Drive')], default='auto', help_text='Use Auto para detectar pelo link, ou escolha YouTube/Google Drive/Google Cloud manualmente.', max_length=20, verbose_name='Origem do video'),
        ),
    ]
