# Generated by Django 5.1.15 on 2026-07-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_enrollment_access_source_enrollment_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='wix_url',
            field=models.URLField(blank=True, help_text='Se preenchido, Entrar al curso abre este link no Wix. Se vazio, mostra Acceso en configuracion.', null=True, verbose_name='URL do curso no Wix'),
        ),
    ]
