# Generated by Django 5.1.15 on 2026-07-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_course_wix_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacroQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Anatomía', 'Anatomía'), ('Histología', 'Histología'), ('Biología', 'Biología')], max_length=50)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explanation', models.TextField(blank=True, help_text='Explicación mostrada tras fallar', null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='enrollmenthistory',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Historial de MatrÃ\xadcula', 'verbose_name_plural': 'Historiales de MatrÃ\xadculas'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-payment_date'], 'verbose_name': 'HistÃ³rico de Pagamento', 'verbose_name_plural': 'HistÃ³rico de Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='podcastepisode',
            options={'ordering': ['order'], 'verbose_name': 'EpisÃ³dio de Podcast', 'verbose_name_plural': 'EpisÃ³dios de Podcast'},
        ),
        migrations.AlterField(
            model_name='deck',
            name='category',
            field=models.CharField(default='General', max_length=100, verbose_name='CategorÃ\xada'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo del Mazo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='access_source',
            field=models.CharField(choices=[('wix', 'Wix Webhook'), ('transferencia', 'Transferencia Bancaria'), ('cortesia', 'CortesÃ\xada/Beca'), ('ajuste_manual', 'Ajuste Manual Staff')], default='wix', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmenthistory',
            name='action',
            field=models.CharField(choices=[('create', 'CreaciÃ³n'), ('extend', 'ExtensiÃ³n'), ('revoke', 'RevocaciÃ³n'), ('expire', 'ExpiraciÃ³n')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='DescriÃ§Ã£o da aula (pode conter links e texto).', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, help_text='Arquivo da aula (vÃ\xaddeo, PDF, etc.)', null=True, upload_to='lessons/files/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='html_content',
            field=models.TextField(blank=True, help_text='Cole o conteÃºdo HTML aqui.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='html_url',
            field=models.URLField(blank=True, help_text='URL do arquivo HTML hospedado (ex: Google Cloud). Se preenchido, o conteÃºdo HTML serÃ¡ carregado via iframe.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('video', 'Video'), ('pdf', 'PDF'), ('html', 'HTML'), ('podcast', 'Podcast'), ('simulacro', 'Simulacro'), ('special_content', 'ConteÃºdo Especial')], default='video', max_length=15),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='simulacro_url',
            field=models.URLField(blank=True, help_text='URL do Simulacro (HTML externo ou arquivo hospedado). SerÃ¡ exibido em iframe.', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='special_content_url',
            field=models.URLField(blank=True, help_text='URL para redirecionamento (ConteÃºdo Especial).', null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL do vÃ\xaddeo (Vimeo, YouTube, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_url',
            field=models.URLField(help_text='Link direto para o arquivo de Ã¡udio.', verbose_name='URL do Ã\x81udio (Cloud)'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='duration',
            field=models.CharField(blank=True, help_text='Opcional', max_length=10, null=True, verbose_name='DuraÃ§Ã£o (ex: 05:30)'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='title',
            field=models.CharField(max_length=200, verbose_name='TÃ\xadtulo do Ã\x81udio'),
        ),
    ]
