# Generated by Django 5.1.15 on 2026-07-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_simulacroquestion_alter_enrollmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacroquestion',
            name='subject',
            field=models.CharField(choices=[('Anatomía', 'Anatomía'), ('Histología', 'Histología'), ('Biología', 'Biología'), ('Embriología', 'Embriología')], max_length=50),
        ),
    ]
