# Generated by Django 5.1.15 on 2026-07-17 01:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Pregunta')),
                ('answer', models.TextField(verbose_name='Respuesta')),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Muy Fácil'), (2, 'Fácil'), (3, 'Medio'), (4, 'Difícil'), (5, 'Muy Difícil')], default=3, verbose_name='Dificultad')),
                ('subject', models.CharField(max_length=200, verbose_name='Materia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Flashcard',
                'verbose_name_plural': 'Flashcards',
                'ordering': ['subject', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFlashcardProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repetitions', models.PositiveIntegerField(default=0)),
                ('consecutive_correct', models.PositiveIntegerField(default=0)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('interval_days', models.PositiveIntegerField(default=0)),
                ('ease_factor', models.FloatField(default=2.5)),
                ('mastery_score', models.FloatField(default=0.0)),
                ('priority', models.FloatField(db_index=True, default=0.0)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('correct_reviews', models.PositiveIntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('next_review_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='flashcards.flashcard')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de Flashcard',
                'verbose_name_plural': 'Progresos de Flashcards',
                'ordering': ['-priority', 'next_review_at'],
                'unique_together': {('student', 'flashcard')},
            },
        ),
    ]
