# Generated by Django 5.1.15 on 2026-07-17 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Racha Actual')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Racha Máxima')),
                ('last_study_date', models.DateField(blank=True, null=True, verbose_name='Última Fecha de Estudio')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha de Estudio',
                'verbose_name_plural': 'Rachas de Estudio',
            },
        ),
    ]
