# Generated by Django 5.1.15 on 2026-07-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='topic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Tema/Tópico'),
        ),
    ]
